# Generated by Django 4.0.1 on 2022-11-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='of_friends',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='message.friend'),
        ),
    ]
