# Generated by Django 4.0.1 on 2022-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_conversation_of_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
    ]
