# Generated by Django 4.1.3 on 2022-12-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_server_server_message_server_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='image',
        ),
    ]
